global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Text;
global using System.Text.Json.Serialization;
global using System.Threading;
global using System.Windows;
global using System.Windows.Data;
global using flier268.Win32API;
global using User32 = MapleStory_HealthKeeper.Plugin.User32;
global using PropertyChanged;
global using ScriptMaster.Core;
global using WindowsHook;